# Generated by Django 3.2.4 on 2021-06-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='position',
            new_name='positions',
        ),
    ]
